[package]
name = "rust_nes"
version = "0.1.0"
authors = ["xxrl <837951112@qq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = { version = "0.4", features = ["std"] }
sfml = "0.16.0"
ini = "1.3.0"
queues = "1.0.2"
clap = { version = "3.0.0-rc.7", features = ["derive"] }