[package]
name = "rust_nes"
version = "0.1.0"
authors = ["xxrl <837951112@qq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
build = "src/build.rs"

[dependencies]
clap = { version = "3.0.0-rc.7", features = ["derive"] }
log = { version = "0.4", features = ["std"] }
lazy_static = "1.4.0"
serde = { version = "1.0", features = ["derive"] }
serde_bytes = "0.11.5"
serde_json = "1.0.59"
ini = "1.3.0"
queues = "1.0.2"
portaudio = {version="0.7.0", optional = true}
image = { version ="0.23.12", features = ["rgb"]}

# sfml = { version = "0.16.0", optional = true}

glfw = { version = "0.42.0" ,optional = true}
gl = { version = "0.14.0" ,optional = true}

sdl2 = { version = "0.35.2" ,optional = true}

android_logger = {version = "0.11.0", optional = true}
jni = { version = "0.19.0", default-features = false }

[build-dependencies]
dunce = "1.0"

[profile.release]
lto = true

[lib]
name = "rust_nes"
crate-type = ["cdylib", "lib"]


[[bin]]
name = "emulator"
path = "src/main.rs"

[features]
default = ["use_sdl2"]
use_gl = ["gl", "glfw", "portaudio"]
use_sdl2 = ["sdl2", "android_logger"]
