[package]
name = "rust_nes"
version = "0.1.0"
authors = ["xxrl <837951112@qq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.0.0-rc.7", features = ["derive"] }
log = { version = "0.4", features = ["std"] }
lazy_static = "1.4.0"
serde = { version = "1.0", features = ["derive"] }
serde_bytes = "0.11.5"
serde_json = "1.0.59"
ini = "1.3.0"
queues = "1.0.2"
portaudio = "0.7.0"
image = { version ="0.23.12", features = ["rgb"]}

sfml = { version = "0.16.0", optional = true}

glfw = { version = "0.42.0", optional = true}
gl = { version = "0.14.0", optional = true}
[features]
default = ["use_gl"]
use_gl = ["gl", "glfw"]
use_sfml = ["sfml"]
