name: build

on:
  push:
    branches:
      - main

jobs:
  linux-binaries:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install stable
        uses: dtolnay/rust-toolchain@stable
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev
      
      - name: Build
        run: cargo build --release
